apiVersion: 1.0.0
publisher: codercom
name: cdr/code-server/latest
version: latest
type: Che Editor
displayName: code-server
title: Visual Studio Code - Web (code-server)
description: An open source distribution of Visual Studio Code as a cloud IDE
icon: https://raw.githubusercontent.com/sr229/discord-open-source/master/logos/code-server.svg
repository: 'https://github.com/cdr/code-server'
category: Editor
  endpoints: 
    - name: code-server
      public: true
      targetPort: 8080
      attributes:
        protocol: http
        discoverable: true
  containers:
    - image: "codercom/code-server:latest"
      name: code-server
      memoryLimit:  "1024M"
      volumes:
        - mountPath: /home/coder/.local/share/code-server
          name: user-data
          ephemeral: true
      ports:
        - exposedPort: 8080
      mountSources: true
