version: 1.0.0
publisher: codercom
editors:
  - id: latest
    title: VS Code Editor
    displayName: vs-code
    description: VS Code Editor for Eclipse che
    icon: https://raw.githubusercontent.com/theia-ide/theia/master/logo/theia-logo-no-text-black.svg?sanitize=true
    repository: https://github.com/cdr/code-server
    containers:
      - name: vscode
        type: dockerimage
        image: 'codercom/code-server:latest'
        memoryLimit: "512M"
        
