version: 1.0.0
publisher: suyashg
editors:
  - id: codercom/code-server
    title: VS Code Editor
    displayName: vs-code
    description: VS Code Editor for Eclipse che
    icon: https://raw.githubusercontent.com/theia-ide/theia/master/logo/theia-logo-no-text-black.svg?sanitize=true
    repository: https://github.com/cdr/code-server
    firstPublicationDate: "2021-01-01"
    endpoints:
      - name: "vscode"
        public: true
        targetPort: 8080
        attributes:
          protocol: http
          type: ide
          secure: true
          cookiesAuthEnabled: true
          discoverable: false
    containers:
      - name: vscode
        image: codercom/code-server:latest
        mountSources: true
        ports:
          - exposedPort: 8080
        memoryLimit: "512M"
        
