version: 1.0.0
publisher: codercom
editors:
  - id: cdr/code-server/latest
    title: Visual Studio Code - Web (code-server)
    displayName: code-server
    description: An open source distribution of Visual Studio Code as a cloud IDE
    icon: https://raw.githubusercontent.com/sr229/discord-open-source/master/logos/code-server.svg
    repository: 'https://github.com/cdr/code-server'
    firstPublicationDate: "2020-11-03"
    endpoints:
      - name: code-server
        targetPort: 8080
        exposure: public
        protocol: http
        attributes:
          type: main
    containers:
      - name: code-server
        image: "codercom/code-server:latest"
        volumeMounts:
          - name: user-data
            path: /home/coder/.local/share/code-server
        mountSources: true
        ports:
          - exposedPort: 8080
        memoryLimit: 1024M
        
